version: "3"
services:
  localtrst:
    image: "ghcr.io/trstlabs/localtrst:latest"
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
      - "9091:9091"
      - "1317:1317"
      - "26660:26660"
      # faucet
      - "5000:5000"
    environment:
      CHAINID: "trstdev-1"
      LOG_LEVEL: "info"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:26657"]
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 30s
  localtrst-2:
    image: "ghcr.io/trstlabs/localtrst:latest"
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "36657:26657"
      - "36656:26656"
      - "9391:9091"
      - "9390:9090"
      - "3317:1317"
      # faucet
      - "5300:5000"
    environment:
      CHAINID: "trstdev-2"
      LOG_LEVEL: "info"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:26657"]
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 30s
  localjuno:
    image: "ghcr.io/cosmoscontracts/juno:13.0.0"
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "46657:26657"
      - "46656:26656"
      - "9491:9091"
      - "9490:9090"
      - "4317:1317"
    environment:
      STAKE_TOKEN: "ujunox"
      UNSAFE_CORS: "false"
    entrypoint:
      [
        "./setup_and_run.sh",
        "juno14fgn7zcxpkcsgeat89ukvxm7h2lg4h6tmduyul",
        "juno16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y",
        "juno1ykql5ktedxkpjszj5trzu8f5dxajvgv9tupqpe",
        juno1he7t2wxzpmfuxfrw7qjg52vu4qljq3l59pfwn3
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:26657"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
  relayer:
    image: ghcr.io/cosmos/relayer:v2.3.0
    ports:
      - "5183:5183"
    volumes:
      - ./rly-run.sh:/app/rly-run.sh:ro
      - ./relayer/interchain-acc-config:/rlyconfig:ro
    command: sh /app/rly-run.sh
    depends_on:
      localtrst:
        condition: service_healthy
      localtrst-2:
        condition: service_healthy
      # localjuno:
      #   condition: service_healthy
