// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intento/claim/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "github.com/cosmos/gogoproto/types"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the claim module's parameters.
type Params struct {
	AirdropStartTime   time.Time     `protobuf:"bytes,1,opt,name=airdrop_start_time,json=airdropStartTime,proto3,stdtime" json:"airdrop_start_time" yaml:"airdrop_start_time"`
	DurationUntilDecay time.Duration `protobuf:"bytes,2,opt,name=duration_until_decay,json=durationUntilDecay,proto3,stdduration" json:"duration_until_decay,omitempty" yaml:"duration_until_decay"`
	DurationOfDecay    time.Duration `protobuf:"bytes,3,opt,name=duration_of_decay,json=durationOfDecay,proto3,stdduration" json:"duration_of_decay,omitempty" yaml:"duration_of_decay"`
	// denom of claimable asset
	ClaimDenom             string          `protobuf:"bytes,4,opt,name=claim_denom,json=claimDenom,proto3" json:"claim_denom,omitempty"`
	DurationVestingPeriods []time.Duration `protobuf:"bytes,5,rep,name=duration_vesting_periods,json=durationVestingPeriods,proto3,stdduration" json:"duration_vesting_periods,omitempty" yaml:"duration_vesting_periods"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b54bcf3939fc539e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAirdropStartTime() time.Time {
	if m != nil {
		return m.AirdropStartTime
	}
	return time.Time{}
}

func (m *Params) GetDurationUntilDecay() time.Duration {
	if m != nil {
		return m.DurationUntilDecay
	}
	return 0
}

func (m *Params) GetDurationOfDecay() time.Duration {
	if m != nil {
		return m.DurationOfDecay
	}
	return 0
}

func (m *Params) GetClaimDenom() string {
	if m != nil {
		return m.ClaimDenom
	}
	return ""
}

func (m *Params) GetDurationVestingPeriods() []time.Duration {
	if m != nil {
		return m.DurationVestingPeriods
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "intento.claim.v1beta1.Params")
}

func init() {
	proto.RegisterFile("intento/claim/v1beta1/params.proto", fileDescriptor_b54bcf3939fc539e)
}

var fileDescriptor_b54bcf3939fc539e = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0xc7, 0x73, 0xb4, 0x54, 0xc2, 0x1d, 0x00, 0xab, 0x20, 0x37, 0x95, 0x7c, 0x91, 0x25, 0xa4,
	0x22, 0x21, 0x9f, 0x0a, 0x1b, 0x63, 0x9a, 0x85, 0x89, 0x52, 0x5e, 0x06, 0x16, 0xeb, 0x1c, 0x5f,
	0xcc, 0x49, 0x3e, 0x9f, 0x75, 0xf7, 0xa4, 0x22, 0x5f, 0x81, 0xa9, 0x13, 0xe2, 0x13, 0xf0, 0x59,
	0x3a, 0x76, 0x64, 0x0a, 0x28, 0x99, 0x60, 0xec, 0x27, 0x40, 0xf7, 0x56, 0xa9, 0x49, 0xa0, 0x9b,
	0xfd, 0xfc, 0x7f, 0xcf, 0xf3, 0xfc, 0x4e, 0xba, 0x8b, 0x32, 0xde, 0x02, 0x6b, 0x41, 0x92, 0x71,
	0x43, 0xb9, 0x20, 0x67, 0x47, 0x25, 0x03, 0x7a, 0x44, 0x3a, 0xaa, 0xa8, 0xd0, 0x79, 0xa7, 0x24,
	0xc8, 0xf8, 0x91, 0x67, 0x72, 0xcb, 0xe4, 0x9e, 0xe9, 0xef, 0xd5, 0xb2, 0x96, 0x96, 0x20, 0xe6,
	0xcb, 0xc1, 0xfd, 0xb4, 0x96, 0xb2, 0x6e, 0x18, 0xb1, 0x7f, 0xe5, 0x74, 0x42, 0xaa, 0xa9, 0xa2,
	0xc0, 0x65, 0xeb, 0x73, 0xbc, 0x9a, 0x03, 0x17, 0x4c, 0x03, 0x15, 0x9d, 0x03, 0xb2, 0xdf, 0xdb,
	0xd1, 0xce, 0x89, 0x5d, 0x1f, 0xcb, 0x28, 0xa6, 0x5c, 0x55, 0x4a, 0x76, 0x85, 0x06, 0xaa, 0xa0,
	0x30, 0x6c, 0x82, 0x06, 0xe8, 0x70, 0xf7, 0x79, 0x3f, 0x77, 0x83, 0xf2, 0x30, 0x28, 0x7f, 0x17,
	0x06, 0x0d, 0x9f, 0x5c, 0xcc, 0x71, 0xef, 0x6a, 0x8e, 0xf7, 0x67, 0x54, 0x34, 0x2f, 0xb3, 0xf5,
	0x19, 0xd9, 0xf9, 0x4f, 0x8c, 0x4e, 0x1f, 0xf8, 0xe0, 0xad, 0xa9, 0x9b, 0xee, 0xf8, 0x2b, 0x8a,
	0xf6, 0x82, 0x6f, 0x31, 0x6d, 0x81, 0x37, 0x45, 0xc5, 0xc6, 0x74, 0x96, 0xdc, 0xb1, 0x3b, 0xf7,
	0xd7, 0x76, 0x8e, 0x3c, 0x3c, 0x7c, 0x65, 0x56, 0xfe, 0x99, 0xe3, 0x74, 0x53, 0xfb, 0x33, 0x29,
	0x38, 0x30, 0xd1, 0xc1, 0xec, 0x6a, 0x8e, 0x0f, 0x9c, 0xd4, 0x26, 0x2e, 0xfb, 0x66, 0xb4, 0xe2,
	0x10, 0xbd, 0x37, 0xc9, 0xc8, 0x04, 0xf1, 0x17, 0x14, 0x3d, 0xbc, 0xee, 0x90, 0x13, 0x6f, 0xb5,
	0x75, 0x9b, 0xd5, 0xb1, 0xb7, 0x3a, 0x58, 0xeb, 0xbd, 0xa1, 0x94, 0xac, 0x28, 0x05, 0xc8, 0xf9,
	0xdc, 0x0f, 0xf5, 0xd7, 0x13, 0x27, 0x83, 0xa3, 0x5d, 0x7b, 0x13, 0x8a, 0x8a, 0xb5, 0x52, 0x24,
	0xdb, 0x03, 0x74, 0x78, 0xef, 0x34, 0xb2, 0xa5, 0x91, 0xa9, 0xc4, 0xdf, 0x51, 0x94, 0x5c, 0x0f,
	0x3b, 0x63, 0x1a, 0x78, 0x5b, 0x17, 0x1d, 0x53, 0x5c, 0x56, 0x3a, 0xb9, 0x3b, 0xd8, 0xfa, 0xbf,
	0xf4, 0x1b, 0x2f, 0x9d, 0xfd, 0x6b, 0xc4, 0x0d, 0x77, 0xbc, 0xe2, 0xbe, 0xc2, 0xba, 0x23, 0x3c,
	0x0e, 0xf1, 0x07, 0x97, 0x9e, 0xb8, 0x70, 0x78, 0x7c, 0xb1, 0x48, 0xd1, 0xe5, 0x22, 0x45, 0xbf,
	0x16, 0x29, 0x3a, 0x5f, 0xa6, 0xbd, 0xcb, 0x65, 0xda, 0xfb, 0xb1, 0x4c, 0x7b, 0x1f, 0x9f, 0xd6,
	0x1c, 0x3e, 0x4d, 0xcb, 0x7c, 0x2c, 0x05, 0x01, 0xa5, 0xa1, 0xa1, 0xa5, 0x26, 0xe1, 0xad, 0x7c,
	0xf6, 0xaf, 0x05, 0x66, 0x1d, 0xd3, 0xe5, 0x8e, 0x3d, 0xc2, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe2, 0xed, 0x74, 0x8d, 0x4b, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DurationVestingPeriods) > 0 {
		for iNdEx := len(m.DurationVestingPeriods) - 1; iNdEx >= 0; iNdEx-- {
			n, err := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.DurationVestingPeriods[iNdEx], dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationVestingPeriods[iNdEx]):])
			if err != nil {
				return 0, err
			}
			i -= n
			i = encodeVarintParams(dAtA, i, uint64(n))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ClaimDenom) > 0 {
		i -= len(m.ClaimDenom)
		copy(dAtA[i:], m.ClaimDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ClaimDenom)))
		i--
		dAtA[i] = 0x22
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.DurationOfDecay, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationOfDecay):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.DurationUntilDecay, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationUntilDecay):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.AirdropStartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.AirdropStartTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.AirdropStartTime)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationUntilDecay)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.DurationOfDecay)
	n += 1 + l + sovParams(uint64(l))
	l = len(m.ClaimDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.DurationVestingPeriods) > 0 {
		for _, e := range m.DurationVestingPeriods {
			l = github_com_gogo_protobuf_types.SizeOfStdDuration(e)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropStartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.AirdropStartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationUntilDecay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.DurationUntilDecay, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationOfDecay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.DurationOfDecay, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationVestingPeriods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DurationVestingPeriods = append(m.DurationVestingPeriods, time.Duration(0))
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&(m.DurationVestingPeriods[len(m.DurationVestingPeriods)-1]), dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
