FROM golang:1.20-alpine AS builder

WORKDIR /opt/

RUN set -eux; apk add --no-cache ca-certificates build-base git;

RUN git clone https://github.com/neutron-org/neutron/ \
    && cd neutron \
    && git checkout v1.0.4

WORKDIR /opt/neutron

RUN WASMVM_VERSION=$(go list -m github.com/CosmWasm/wasmvm | cut -d ' ' -f 2) \
    && wget https://github.com/CosmWasm/wasmvm/releases/download/$WASMVM_VERSION/libwasmvm_muslc.$(uname -m).a \
    -O /lib/libwasmvm_muslc.a

RUN LEDGER_ENABLED=false BUILD_TAGS=muslc LINK_STATICALLY=true make build

FROM alpine:3.16
COPY --from=builder /opt/neutron/bin/neutrond /usr/local/bin/
RUN apk add bash vim \
    && addgroup -g 1000 neutron \
    && adduser -S -h /home/neutron -D neutron -u 1000 -G neutron

USER 1000
WORKDIR /home/neutron

EXPOSE 26657 26656 1317 9090

CMD ["neutrond", "start"]
