
[global]
# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'info'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'trstdev-1'
rpc_addr = 'http://localtrst-1:26657'
grpc_addr = 'http://localtrst-1:9090'
websocket_addr = 'ws://localtrst-1:26657/websocket'

rpc_timeout = '20s'
account_prefix = 'trust'
key_name = 'localtrst-key'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 2000000
gas_price = { price = 1, denom = 'utrst' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '20s'
trusting_period = '2days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

#[chains.packet_filter]
#policy = 'allow'
#list = [
#    ['wasm.*', '*'],
#    ['transfer', '*']
#]

[[chains]]
id = 'trstdev-2'
rpc_addr = 'http://localtrst-2:26657'
grpc_addr = 'http://localtrst-2:9090'
websocket_addr = 'ws://localtrst-2:26657/websocket'

rpc_timeout = '20s'
account_prefix = 'trust'
key_name = 'localtrst2-key'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 2000000
gas_price = { price = 1, denom = 'utrst' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '20s'
trusting_period = '2days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

#[chains.packet_filter]
#policy = 'allow'
#list = [
#    ['wasm.*', '*'],
#    ['transfer', '*']
#]
