// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intento/intent/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "github.com/cosmos/gogoproto/types"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the params for activeness of Actions on governance proposals.
type Params struct {
	ActionFundsCommission      int64 `protobuf:"varint,1,opt,name=ActionFundsCommission,proto3" json:"ActionFundsCommission,omitempty"`
	ActionFlexFeeMul           int64 `protobuf:"varint,2,opt,name=ActionFlexFeeMul,proto3" json:"ActionFlexFeeMul,omitempty"`
	ActionConstantFee          int64 `protobuf:"varint,3,opt,name=ActionConstantFee,proto3" json:"ActionConstantFee,omitempty"`
	RecurringActionConstantFee int64 `protobuf:"varint,4,opt,name=RecurringActionConstantFee,proto3" json:"RecurringActionConstantFee,omitempty"`
	//  Maximum period for self-executing Action
	MaxActionDuration time.Duration `protobuf:"bytes,5,opt,name=MaxActionDuration,proto3,stdduration" json:"max_action_duration,omitempty"`
	//  Minimum period for self-executing Action
	MinActionDuration time.Duration `protobuf:"bytes,6,opt,name=MinActionDuration,proto3,stdduration" json:"min_action_duration,omitempty"`
	//  Minimum period for self-executing Action
	MinActionInterval time.Duration `protobuf:"bytes,8,opt,name=MinActionInterval,proto3,stdduration" json:"min_action_interval,omitempty"`
	//relayer rewards in uinto for each message type 0=SDK,1=Wasm, 2=Osmo. Rewards are in uinto and topped up in the module account by alloc module.
	RelayerRewards []int64 `protobuf:"varint,9,rep,packed,name=relayer_rewards,json=relayerRewards,proto3" json:"relayer_rewards,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f869cd012e617b1c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "intento.intent.v1beta1.Params")
}

func init() {
	proto.RegisterFile("intento/intent/v1beta1/params.proto", fileDescriptor_f869cd012e617b1c)
}

var fileDescriptor_f869cd012e617b1c = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0xcb, 0xd3, 0x30,
	0x18, 0x6f, 0xec, 0x1c, 0x1a, 0x41, 0x7d, 0x8b, 0x4a, 0x1d, 0x98, 0x0e, 0x3d, 0x38, 0x5f, 0x5e,
	0x1a, 0x5e, 0xf5, 0xe4, 0x41, 0x70, 0x93, 0x81, 0xe0, 0x40, 0x7a, 0xf4, 0x32, 0xd2, 0x2d, 0xd6,
	0x40, 0x9b, 0x94, 0x24, 0x9d, 0xdd, 0xb7, 0xf0, 0xb8, 0xa3, 0x47, 0x3f, 0xca, 0x8e, 0x3b, 0x7a,
	0x9a, 0xda, 0xde, 0xfc, 0x14, 0xb2, 0xa4, 0x3d, 0xb8, 0xfa, 0x8f, 0xf7, 0x94, 0xf6, 0xf7, 0x97,
	0xe7, 0x81, 0x07, 0x3e, 0x60, 0x5c, 0x53, 0xae, 0x05, 0xb6, 0x2f, 0x5e, 0x9d, 0xc7, 0x54, 0x93,
	0x73, 0x9c, 0x13, 0x49, 0x32, 0x15, 0xe6, 0x52, 0x68, 0xe1, 0xdd, 0x69, 0x44, 0xa1, 0x7d, 0xc3,
	0x46, 0x34, 0xb8, 0x95, 0x88, 0x44, 0x18, 0x09, 0x3e, 0x7c, 0x59, 0xf5, 0x00, 0x25, 0x42, 0x24,
	0x29, 0xc5, 0xe6, 0x2f, 0x2e, 0xde, 0xe1, 0x65, 0x21, 0x89, 0x66, 0x82, 0x5b, 0xfe, 0x7e, 0xdd,
	0x83, 0xfd, 0x37, 0x26, 0xde, 0x7b, 0x0a, 0x6f, 0xbf, 0x58, 0x1c, 0xa8, 0x69, 0xc1, 0x97, 0x6a,
	0x22, 0xb2, 0x8c, 0x29, 0xc5, 0x04, 0xf7, 0xc1, 0x10, 0x8c, 0xdc, 0xe8, 0xf7, 0xa4, 0x77, 0x0a,
	0x6f, 0x36, 0x44, 0x4a, 0xcb, 0x29, 0xa5, 0xb3, 0x22, 0xf5, 0x2f, 0x19, 0x43, 0x07, 0xf7, 0xce,
	0xe0, 0x89, 0xc5, 0x26, 0x82, 0x2b, 0x4d, 0xb8, 0x9e, 0x52, 0xea, 0xbb, 0x46, 0xdc, 0x25, 0xbc,
	0xe7, 0x70, 0x10, 0xd1, 0x45, 0x21, 0x25, 0xe3, 0x49, 0xd7, 0xd6, 0x33, 0xb6, 0xbf, 0x28, 0x3c,
	0x09, 0x4f, 0x66, 0xa4, 0xb4, 0xf8, 0xcb, 0x66, 0x6a, 0xff, 0xf2, 0x10, 0x8c, 0xae, 0x3d, 0xbe,
	0x1b, 0xda, 0xb5, 0x84, 0xed, 0x5a, 0xc2, 0x56, 0x30, 0x7e, 0xb4, 0xdd, 0x07, 0xce, 0x8f, 0x7d,
	0x70, 0x2f, 0x23, 0xe5, 0x9c, 0x18, 0xf3, 0xbc, 0xdd, 0xd9, 0x99, 0xc8, 0x98, 0xa6, 0x59, 0xae,
	0xd7, 0x9b, 0xaf, 0x01, 0x88, 0xba, 0xf1, 0xa6, 0x93, 0xf1, 0xa3, 0xce, 0xfe, 0xff, 0x77, 0x32,
	0xfe, 0xcf, 0xce, 0xe3, 0xf8, 0x5f, 0x3a, 0x5f, 0x71, 0x4d, 0xe5, 0x8a, 0xa4, 0xfe, 0x95, 0x8b,
	0x74, 0xb2, 0xc6, 0xfd, 0xc7, 0xce, 0x36, 0xde, 0x7b, 0x08, 0x6f, 0x48, 0x9a, 0x92, 0x35, 0x95,
	0x73, 0x49, 0x3f, 0x10, 0xb9, 0x54, 0xfe, 0xd5, 0xa1, 0x3b, 0x72, 0xa3, 0xeb, 0x0d, 0x1c, 0x59,
	0xf4, 0x59, 0x6f, 0xf3, 0x29, 0x70, 0xc6, 0xaf, 0xb7, 0xdf, 0x91, 0xf3, 0xb9, 0x42, 0x60, 0x5b,
	0x21, 0xb0, 0xab, 0x10, 0xf8, 0x56, 0x21, 0xf0, 0xb1, 0x46, 0xce, 0xae, 0x46, 0xce, 0x97, 0x1a,
	0x39, 0x6f, 0x4f, 0x13, 0xa6, 0xdf, 0x17, 0x71, 0xb8, 0x10, 0x19, 0xd6, 0x52, 0xe9, 0x94, 0xc4,
	0x0a, 0xb7, 0xe7, 0x50, 0xb6, 0x07, 0xa1, 0xd7, 0x39, 0x55, 0x71, 0xdf, 0x4c, 0xf3, 0xe4, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xe2, 0x44, 0x33, 0x2f, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ActionFundsCommission != that1.ActionFundsCommission {
		return false
	}
	if this.ActionFlexFeeMul != that1.ActionFlexFeeMul {
		return false
	}
	if this.ActionConstantFee != that1.ActionConstantFee {
		return false
	}
	if this.RecurringActionConstantFee != that1.RecurringActionConstantFee {
		return false
	}
	if this.MaxActionDuration != that1.MaxActionDuration {
		return false
	}
	if this.MinActionDuration != that1.MinActionDuration {
		return false
	}
	if this.MinActionInterval != that1.MinActionInterval {
		return false
	}
	if len(this.RelayerRewards) != len(that1.RelayerRewards) {
		return false
	}
	for i := range this.RelayerRewards {
		if this.RelayerRewards[i] != that1.RelayerRewards[i] {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayerRewards) > 0 {
		dAtA2 := make([]byte, len(m.RelayerRewards)*10)
		var j1 int
		for _, num1 := range m.RelayerRewards {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintParams(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x4a
	}
	n3, err3 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.MinActionInterval, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.MinActionInterval):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x42
	n4, err4 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.MinActionDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.MinActionDuration):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintParams(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x32
	n5, err5 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.MaxActionDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.MaxActionDuration):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintParams(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x2a
	if m.RecurringActionConstantFee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RecurringActionConstantFee))
		i--
		dAtA[i] = 0x20
	}
	if m.ActionConstantFee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionConstantFee))
		i--
		dAtA[i] = 0x18
	}
	if m.ActionFlexFeeMul != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFlexFeeMul))
		i--
		dAtA[i] = 0x10
	}
	if m.ActionFundsCommission != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFundsCommission))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ActionFundsCommission != 0 {
		n += 1 + sovParams(uint64(m.ActionFundsCommission))
	}
	if m.ActionFlexFeeMul != 0 {
		n += 1 + sovParams(uint64(m.ActionFlexFeeMul))
	}
	if m.ActionConstantFee != 0 {
		n += 1 + sovParams(uint64(m.ActionConstantFee))
	}
	if m.RecurringActionConstantFee != 0 {
		n += 1 + sovParams(uint64(m.RecurringActionConstantFee))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.MaxActionDuration)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.MinActionDuration)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.MinActionInterval)
	n += 1 + l + sovParams(uint64(l))
	if len(m.RelayerRewards) > 0 {
		l = 0
		for _, e := range m.RelayerRewards {
			l += sovParams(uint64(e))
		}
		n += 1 + sovParams(uint64(l)) + l
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFundsCommission", wireType)
			}
			m.ActionFundsCommission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFundsCommission |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFlexFeeMul", wireType)
			}
			m.ActionFlexFeeMul = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFlexFeeMul |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionConstantFee", wireType)
			}
			m.ActionConstantFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionConstantFee |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecurringActionConstantFee", wireType)
			}
			m.RecurringActionConstantFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecurringActionConstantFee |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActionDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.MaxActionDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinActionDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.MinActionDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinActionInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.MinActionInterval, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RelayerRewards = append(m.RelayerRewards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParams
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParams
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.RelayerRewards) == 0 {
					m.RelayerRewards = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RelayerRewards = append(m.RelayerRewards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerRewards", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
