version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: user1
  coins:
  - 200000000uinto
- name: user2
  coins:
  - 500000uinto
- name: user3
  coins:
  - 50000uinto
- name: user4
  coins:
  - 50000uinto
- name: faucet
  coins:
  - 1000000000uinto
  mnemonic: yellow reveal rubber dumb picture cargo valid cover define inner demand
    solve panel behave analyst build edit stereo hope initial feed rare bleak army
faucet:
  name: null
  coins: []
  host: 0.0.0.0:4500
client:
  vuex:
    path: js
genesis:
  app_state:
    staking:
      params:
        bond_denom: uinto
validators:
- name: user1
  bonded: 100000000uinto
