name: Build Image on New Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the INTO version tag"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        run: |
          version=${{ github.event.inputs.version || github.ref }}
          version=${version#refs/tags/}
          echo "version=$version" >> $GITHUB_ENV
          echo "Version: $version"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Image
        env:
          DOCKER_BUILDKIT: 1
        shell: bash
        run: |
          tag=ghcr.io/trstlabs/intento:${{ env.version }}
          docker build -t $tag .
          docker push $tag